ALTER TABLE "SNWD_PD" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$uc_SNWD_PD~PID$',	'CLIENT',	'PRODUCT_ID'))
ALTER TABLE "SNWD_PD" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$CLIENT$DESC_GUID$',	'CLIENT',	'DESC_GUID'))
ALTER TABLE "SNWD_PD" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$CLIENT$NAME_GUID$',	'CLIENT',	'NAME_GUID'))

ALTER TABLE "SNWD_TEXTS" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$uc_SNWD_TEXTS~PAR$',	'CLIENT',	'PARENT_KEY',	'LANGUAGE'))
ALTER TABLE "SNWD_TEXTS" WITH PARAMETERS ('CONCAT_ATTRIBUTE'=('$CLIENT$PARENT_KEY$',	'CLIENT',	'PARENT_KEY'))


CREATE UNIQUE INDEX "SNWD_PD~PID" ON "SNWD_PD" ( "CLIENT" ASC,	 "PRODUCT_ID" ASC ) NONLEAF PARTIAL KEY LENGTH 1
CREATE UNIQUE INDEX "SNWD_TEXTS~PAR" ON "SNWD_TEXTS" ( "CLIENT" ASC,	 "PARENT_KEY" ASC,	 "LANGUAGE" ASC ) NONLEAF PARTIAL KEY LENGTH 1
CREATE FULLTEXT INDEX SNWD_TEXTS_TEXT ON "SNWD_TEXTS"(TEXT) FAST PREPROCESS OFF FUZZY SEARCH INDEX ON